packagegroup-parallelogram: Change PACKAGE_ARCH
Packagegroups are allarch by default, but since some packages pulled in
by this packagegroup get renamed, it should be set to TUNE_PKGARCH.
Fixes errors like:

	ERROR: packagegroup-parallelogram-1.0-r0 do_package_write_ipk: An
	allarch packagegroup shouldn't depend on packages which are
	dynamically renamed (ell to libell0)